server:
  port: 8082
spring:
  application:
    name: mini-pay-point
  profiles:
    include: secret
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true